# Generated by Django 4.2.16 on 2024-12-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_faculty_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'subject', 'date', 'period')},
        ),
    ]
